#!/bin/sh
ENV_FILENAME="/app/.env"

# Create .env file
touch $ENV_FILENAME

# ETHEREUM env vars
echo "VITE_ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL" >> $ENV_FILENAME
echo "VITE_ETHEREUM_EXPLORER_URL=$ETHEREUM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_ETHEREUM_BRIDGE_CONTRACT_ADDRESS=$ETHEREUM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=$ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT" >> $ENV_FILENAME
echo "VITE_ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=$ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_ETHEREUM_ROLLUP_MANAGER_ADDRESS=$ETHEREUM_ROLLUP_MANAGER_ADDRESS" >> $ENV_FILENAME

# POLYGON ZK EVM env vars
echo "VITE_POLYGON_ZK_EVM_RPC_URL=$POLYGON_ZK_EVM_RPC_URL" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_EXPLORER_URL=$POLYGON_ZK_EVM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=$POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_NETWORK_ID=$POLYGON_ZK_EVM_NETWORK_ID" >> $ENV_FILENAME

# BRIDGE API env vars
echo "VITE_BRIDGE_API_URL=$BRIDGE_API_URL" >> $ENV_FILENAME

# FIAT EXCHANGE RATES API env vars
echo "VITE_ENABLE_FIAT_EXCHANGE_RATES=$ENABLE_FIAT_EXCHANGE_RATES" >> $ENV_FILENAME

if [ ! -z "$FIAT_EXCHANGE_RATES_API_URL" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_API_URL=$FIAT_EXCHANGE_RATES_API_URL" >> $ENV_FILENAME
fi

if [ ! -z "$FIAT_EXCHANGE_RATES_API_KEY" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_API_KEY=$FIAT_EXCHANGE_RATES_API_KEY" >> $ENV_FILENAME
fi

if [ ! -z "$FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS=$FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS" >> $ENV_FILENAME
fi

# OUTDATED NETWORK MODAL
echo "VITE_ENABLE_OUTDATED_NETWORK_MODAL=$ENABLE_OUTDATED_NETWORK_MODAL" >> $ENV_FILENAME

if [ ! -z "$OUTDATED_NETWORK_MODAL_TITLE" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_TITLE=$OUTDATED_NETWORK_MODAL_TITLE" >> $ENV_FILENAME
fi

if [ ! -z "$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_1" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_1=$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_1" >> $ENV_FILENAME
fi

if [ ! -z "$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_2" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_2=$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_2" >> $ENV_FILENAME
fi

if [ ! -z "$OUTDATED_NETWORK_MODAL_URL" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_URL=$OUTDATED_NETWORK_MODAL_URL" >> $ENV_FILENAME
fi

# DEPOSIT WARNING
echo "VITE_ENABLE_DEPOSIT_WARNING=$ENABLE_DEPOSIT_WARNING" >> $ENV_FILENAME

# REPORT FORM
echo "VITE_ENABLE_REPORT_FORM=$ENABLE_REPORT_FORM" >> $ENV_FILENAME

if [ ! -z "$REPORT_FORM_URL" ];
then
  echo "VITE_REPORT_FORM_URL=$REPORT_FORM_URL" >> $ENV_FILENAME
fi

if [ ! -z "$REPORT_FORM_ERROR_ENTRY" ];
then
  echo "VITE_REPORT_FORM_ERROR_ENTRY=$REPORT_FORM_ERROR_ENTRY" >> $ENV_FILENAME
fi

if [ ! -z "$REPORT_FORM_PLATFORM_ENTRY" ];
then
  echo "VITE_REPORT_FORM_PLATFORM_ENTRY=$REPORT_FORM_PLATFORM_ENTRY" >> $ENV_FILENAME
fi

if [ ! -z "$REPORT_FORM_URL_ENTRY" ];
then
  echo "VITE_REPORT_FORM_URL_ENTRY=$REPORT_FORM_URL_ENTRY" >> $ENV_FILENAME
fi

# BACKGROUND IMAGE
if [ ! -z "$SHOW_BACKGROUND_IMAGE" ];
then
  echo "VITE_SHOW_BACKGROUND_IMAGE=$SHOW_BACKGROUND_IMAGE" >> $ENV_FILENAME
fi

# BRANDING (white-label). VITE_BRAND selects the brand token/asset set at build
# time (src/brands); the rest are per-deployment content. Unset => default brand.
if [ ! -z "$BRAND" ];
then
  echo "VITE_BRAND=$BRAND" >> $ENV_FILENAME
fi

if [ ! -z "$FRONTEND_TYPE" ];
then
  echo "VITE_FRONTEND_TYPE=$FRONTEND_TYPE" >> $ENV_FILENAME
fi

if [ ! -z "$BRAND_COMPONENTS" ];
then
  echo "VITE_BRAND_COMPONENTS=$BRAND_COMPONENTS" >> $ENV_FILENAME
fi

if [ ! -z "$NETWORK_NAME" ];
then
  echo "VITE_NETWORK_NAME=$NETWORK_NAME" >> $ENV_FILENAME
fi

if [ ! -z "$NETWORK_SYMBOL" ];
then
  echo "VITE_NETWORK_SYMBOL=$NETWORK_SYMBOL" >> $ENV_FILENAME
fi

if [ ! -z "$LOGO_PATH" ];
then
  echo "VITE_LOGO_PATH=$LOGO_PATH" >> $ENV_FILENAME
fi

if [ ! -z "$ICON_PATH" ];
then
  echo "VITE_ICON_PATH=$ICON_PATH" >> $ENV_FILENAME
fi

if [ ! -z "$FAVICON_PATH" ];
then
  echo "VITE_FAVICON_PATH=$FAVICON_PATH" >> $ENV_FILENAME
fi

if [ ! -z "$CHAIN_ICON_URL" ];
then
  echo "VITE_CHAIN_ICON_URL=$CHAIN_ICON_URL" >> $ENV_FILENAME
fi

# FAUCET (only used by brands whose faucet is enabled, e.g. teiza)
if [ ! -z "$FAUCET_API_URL" ];
then
  echo "VITE_FAUCET_API_URL=$FAUCET_API_URL" >> $ENV_FILENAME
fi

if [ ! -z "$FAUCET_SERVING_ADDRESS" ];
then
  echo "VITE_FAUCET_SERVING_ADDRESS=$FAUCET_SERVING_ADDRESS" >> $ENV_FILENAME
fi

echo "Generated .env file:"
echo "$(cat /app/.env)"

# Build app
cd /app && npm run build

# Copy nginx config
cp /app/deployment/nginx.conf /etc/nginx/conf.d/default.conf

# Copy app dist
cp -r /app/dist/. /usr/share/nginx/html

# Delete source code
rm -rf /app

# Run nginx
nginx -g 'daemon off;'
